In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [48]:
url = '../../Datasets/house-prices-advanced-regression-techniques/train.csv'
df = pd.read_csv(url, sep=",")
df.head(10)

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   
5   6          50       RL         85.0    14115   Pave   NaN      IR1   
6   7          20       RL         75.0    10084   Pave   NaN      Reg   
7   8          60       RL          NaN    10382   Pave   NaN      IR1   
8   9          50       RM         51.0     6120   Pave   NaN      Reg   
9  10         190       RL         50.0     7420   Pave   NaN      Reg   

  LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
2         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
3         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
4         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
5         Lvl    AllPub  ...        0    NaN  MnPrv        Shed     700   
6         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
7         Lvl    AllPub  ...        0    NaN    NaN        Shed     350   
8         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
9         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   

  MoSold YrSold  SaleType  SaleCondition  SalePrice  
0      2   2008        WD         Normal     208500  
1      5   2007        WD         Normal     181500  
2      9   2008        WD         Normal     223500  
3      2   2006        WD        Abnorml     140000  
4     12   2008        WD         Normal     250000  
5     10   2009        WD         Normal     143000  
6      8   2007        WD         Normal     307000  
7     11   2009        WD         Normal     200000  
8      4   2008        WD        Abnorml     129900  
9      1   2008        WD         Normal     118000  

[10 rows x 81 columns]

In [49]:
y_train = df.SalePrice
print(y_train.head())

0    208500
1    181500
2    223500
3    140000
4    250000
Name: SalePrice, dtype: int64


In [50]:
belirleyici = ['YearBuilt','1stFlrSF','2ndFlrSF','LotArea','YrSold','FullBath','MSSubClass','TotRmsAbvGrd','BedroomAbvGr']

In [38]:
veri_belirleyici = df[belirleyici]
veri_belirleyici.head()

YearBuilt  1stFlrSF  2ndFlrSF  LotArea  YrSold  FullBath  MSSubClass  \
0       2003       856       854     8450    2008         2          60   
1       1976      1262         0     9600    2007         2          20   
2       2001       920       866    11250    2008         2          60   
3       1915       961       756     9550    2006         1          70   
4       2000      1145      1053    14260    2008         2          60   

   TotRmsAbvGrd  BedroomAbvGr  
0             8             3  
1             6             3  
2             6             3  
3             7             3  
4             9             4

In [44]:
from sklearn.tree import DecisionTreeRegressor
dt_model = DecisionTreeRegressor()
dt_model.fit(veri_belirleyici, y_train)
print(dt_model.predict(veri_belirleyici.head()))

[208500. 181500. 223500. 140000. 250000.]


In [45]:
from sklearn.metrics import mean_absolute_error
train_predictions = dt_model.predict(veri_belirleyici)
print(train_predictions)
mean_absolute_error(y_train, train_predictions)

[208500. 181500. 223500. ... 266500. 142125. 147500.]


20.03698630136986

In [46]:
test_url = '../../Datasets/house-prices-advanced-regression-techniques/test.csv'
test = pd.read_csv(test_url)
test_belirleyici = test[belirleyici]
test_predictions = dt_model.predict(test_belirleyici)
print(test_predictions)

[ 94750. 137500. 181000. ... 160000.  93500. 220000.]


In [47]:
submission = pd.DataFrame({'Id': test.Id, 'SalePrice': test_predictions})
submission.to_csv('decision_tree_regressor_submission.csv', index=False)